### ISSUE TITLE
publish new version of crate on crates.io for fix in #12

### ISSUE THREAD

**Issue by mykmelez** [XAMPPRocky/remove_dir_all#13]
Now that #12 has landed, it'd be useful to publish a new version of the crate with that fix on crates.io, so projects that depend on the crates.io distribution can simply update their dependency version to get the fix (instead of having to change their dependency to reference the repository and commit).

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I have just released 0.5.2.

**Comment by mykmelez** [comment]
Thanks, @XAMPPRocky, I really appreciate it!
