### ISSUE TITLE
remove_item is slightly wasteful on syscalls; hardlink ro flag restoration broken.

### ISSUE THREAD

**Issue by rbtcollins** [XAMPPRocky/remove_dir_all#16]
I'm looking at v0.5.2, which uses fs::set_permissions and path.metadata()?.permissions(). These calls on Windows have to indirect via opening the file, then setting the permissions; It would save a syscall to open the file, read the permissions and then set them on the same open file, before reopening with enhanced access. 

Alternatively, since the files permissions are accessed by the read dir iterator in the calling function anyway, passing the actual permissions down, rather than just a boolean extracted from them, would allow skipping the redundant read.

Similarly at the end of the function - and I'll note that because the read only flag restoration is being done on path, not on handle, that it is currently broken and ineffective.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Unfortunately I no longer intend to maintain this repository as I no longer own a Windows machine to be able to test it in on. I'd like for this implementation to merged or superceded in std itself. I outlined this in this thread on https://github.com/rust-lang/rust/issues/29497#issuecomment-573353391 ehuss also mentioned there being a possibly better implementation that could supercede this.

**Comment by rbtcollins** [comment]
Totally fair! I'm happy enough to help care for this crate in the meantime, as we have it as a hard dep in rustup (and cargo too), though I agree that rolling it into std is probably better still. If you'd care to add crates.io permissions, and we could fork this into the nursery, that would at least get it off of your plate in the short term.

BTW: for windows dev some folk I know use VMs from https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ to do windows specific testing, even if they don't have dedicated windows hardware.

**Comment by XAMPPRocky** [comment]
Sorry, for the late reply, that will work with me. I just have to find the time to coordinate moving everything over.

**Comment by rbtcollins** [comment]
Fixed in 0.6
