### ISSUE TITLE
release 0.5.3 changed MSRV to Rust 1.40

### ISSUE THREAD

**Issue by clintfred** [XAMPPRocky/remove_dir_all#26]
Thanks for your work on this library. I ran into an issue that might be of interest to others.

[This commit](https://github.com/XAMPPRocky/remove_dir_all/commit/11ba75fb338f4a3a2c1ee6e99f4dc7bda0c07cd1) changed the MSRV to Rust 1.40. I found this out because my project that was picking up remove_dir_all as a transitive dependency. 0.5.1 was fine with Rust 1.38, but 0.5.3 is not.

My suggestion would be to document the project's MSRV and do at least minor version bumps when the MSRV is changed.

I will paste my original error in case it helps someone else find this.

```
   Compiling remove_dir_all v0.5.3
error[E0658]: `cfg(doctest)` is experimental and subject to change
Error:   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/remove_dir_all-0.5.3/src/lib.rs:12:7
   |
12 | #[cfg(doctest)]
   |       ^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/62210
```

**Comment by lzutao** [comment]
See  #21

**Comment by rbtcollins** [comment]
I think it's reasonable that we document the MRSV... however we should
simply state that we have no specific MSRV other than stable as this is a
volunteer effort for us all.

Rob

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've gone ahead and added a note to the README that explains the MSRV policy as @rbtcollins mentioned.
