### ISSUE TITLE
Issue running under `wine`

### ISSUE THREAD

**Issue by Jake-Shadle** [XAMPPRocky/remove_dir_all#31]
Wine (even in the latest 6.11 version) doesn't implement to entirety of [`SetFileInformationByHandle`](https://github.com/XAMPPRocky/remove_dir_all/blob/9b164cecdb4a0590af68be8b22f9c747402237e3/src/fs.rs#L137-L142), notably in this crate's case, `FILE_DISPOSITION_INFO`, which can cause hangs when used.

I don't consider this a super high priority issue since this can be worked around by just...not calling `remove_dir_all`, but figured I would mention this in case someone else runs up against this issue and/or wants to fix it it by using a fallback method or the like.

**Comment by rbtcollins** [comment]
What's the bug link for this in wine?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! You can also try downgrading to `0.5` in the meantime which does not use `SetFileInformationByHandle` .

**Comment by rbtcollins** [comment]
This has perhaps gotten worse with the TOCTOU fixes? I'll note that rust itself since the overhaul of remove_dir_all in the std library also uses NtCreateFile and SetFileInformationByHandle. I'm very open to non-intrusive patches to support wine users, but ultimately it is on Wine as an emulator, to well, emulate.

**Comment by XAMPPRocky** [comment]
Since the release of the Steamdeck, wine's support has gotten a lot better, and I think this issue might be resolved. Would you be able to confirm @Jake-Shadle?

**Comment by rbtcollins** [comment]
I did a quick check with wine64. Runs without error, but given a tree of symlinks/dirs/files, it didn't delete the symlinks, but the NtCreateFile and SetFileInformationByHandle doesn't seem to be a concrete problem.

```
wine64 --version
wine-5.0.3 (Ubuntu 5.0.3-3ubuntu2)
```

**Comment by XAMPPRocky** [comment]
I'm going to close it for now then, and we can make a issue or re-open if it comes up again.
