### ISSUE TITLE
Crates.io release

### ISSUE THREAD

**Issue by Xaeroxe** [XAMPPRocky/remove_dir_all#43]
Your downstream users could benefit from a crates.io release of https://github.com/XAMPPRocky/remove_dir_all/pull/42. I'd appreciate it!

**Comment by XAMPPRocky** [comment]
@rbtcollins Are you okay with publishing a release of the current state? I can hit publish if so.

**Comment by Xaeroxe** [comment]
@rbtcollins Friendly reminder about this question. I have a PR waiting for resolution of this issue.

**Comment by joshtriplett** [comment]
I'd love to see a release of this (ideally with https://github.com/XAMPPRocky/remove_dir_all/pull/48 also included).

**Comment by rbtcollins** [comment]
Hi, I finally pulled together enough spoons for the security fix I've been prepping. It would benefit from some eyeballs, but needs to remain embargoed I think; if anyone wants to volunteers, that would be helpful.

**Comment by Xaeroxe** [comment]
I'd review it if you'd have me.

**Comment by rbtcollins** [comment]
@XAMPPRocky - when you have time, if you could follow https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/adding-a-collaborator-to-a-repository-security-advisory for @Xaeroxe that would be great.

**Comment by XAMPPRocky** [comment]
Done, you should have received your invitation @Xaeroxe

**Comment by Xaeroxe** [comment]
Got it, thanks

**Comment by XAMPPRocky** [comment]
Merged and published, great work everyone!

@rbtcollins Just fyi, CI is failing on unix machines which is odd. https://github.com/XAMPPRocky/remove_dir_all/actions/runs/4261433709/jobs/7415750973#step:5:10
