### ISSUE TITLE
LICENSE is spelled  i̶n̶c̶o̶r̶r̶e̶c̶t̶l̶y̶ in English English

### ISSUE THREAD

**Issue by Bodhizafa** [XAMPPRocky/remove_dir_all#45]
This repo contains files called 'LICENCE-MIT' and 'LICENCE-APACHE', they should be LICENSE.

This breaks an automatic license scraper used in a build system I work with.

**Comment by Bodhizafa** [comment]
OK I guess faraway places spell it like this, but the files themselves spell it with an S and apparently no other libraries I've seen do this, otherwise it would have broken before. 🤷

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I have no interest in changing it.

**Comment by rbtcollins** [comment]
> files themselves spell it with an S and apparently no other libraries

https://www.grammarly.com/blog/licence-license/ - language is complicated, and in this case the files are nouns, so Licence is entirely appropriate, and to License is the action being undertaken. As the licences themselves come from US institutions its unsurprising that they use US spelling where both nouns and verbs are the same.
