### ISSUE TITLE
CVE ID should be different to the rust-lang.org one.

### ISSUE THREAD

**Issue by rbtcollins** [XAMPPRocky/remove_dir_all#53]
This is on me, but I didn't get the right pattern for referring to the Rust CVE vs this CVE - are we able to get the advisory to have its own distinct CVE? @pietroalbini advises that scanners could be confused by the same CVE ID being used, and since the point of the vuln system is to let people know when they have to fix something, we should help them as much as possible,

**Comment by pietroalbini** [comment]
Not sure if you can *request* an ID from GitHub once the advisory has been published, but it should be possible at least to remove the CVE ID from the advisory.

**Comment by XAMPPRocky** [comment]
I have removed it, let me know if there's something it should be.

**Comment by pietroalbini** [comment]
Thanks! In theory a new CVE ID should be requested, not sure if GitHub allows doing so after the advisory is public. Worst case go [through MITRE](https://www.cve.org/ResourcesSupport/ReportRequest).

**Comment by rbtcollins** [comment]
I don't remember what we did, but all the fixes are public and done and dusted at this point.
