### ISSUE TITLE
automate cargo publishing

### ISSUE THREAD

**Issue by rbtcollins** [XAMPPRocky/remove_dir_all#55]
@XAMPPRocky what do you think of something like https://github.com/Unleash/unleash-client-rust/blob/main/.github/workflows/publish.yaml ?

**Comment by XAMPPRocky** [comment]
I'm totally happy with something like this. I've been looking into adding something like this for all my repos, but haven't gotten there yet (see https://github.com/XAMPPRocky/octocrab/issues/293). I'm happy to use whatever existing solution you have.

**Comment by rbtcollins** [comment]
I'm fairly happy with the linked setup.

Basic properties (could be improved on if needed).

- one of us creates a crates token and puts it in the repo secrets store. I have no access to that as I'm not 'Admin', so you'd need to do this (though I can create the secret if you wish, and one-paste it to you).
- its secrecy is preserved by only having the job run on changes to main|master - other branches, and third party branches won't trigger it.
- to do a release, merge a commit with a new version in Cargo.toml

If you'd like me to setit up, I just need the name of the secret to put in the workflow.

**Comment by XAMPPRocky** [comment]
I've added the variable with the same name as what was in the publish file `CARGO_REGISTRY_TOKEN`, so copying and pasting should just work.

**Comment by rbtcollins** [comment]
https://github.com/XAMPPRocky/remove_dir_all/pull/60
