### ISSUE TITLE
RemoveDir trait is not public

### ISSUE THREAD

**Issue by Xaeroxe** [XAMPPRocky/remove_dir_all#57]
@rbtcollins @XAMPPRocky Was this intentional? It seems like the trait should be public.

**Comment by rbtcollins** [comment]
Hmm, that might be oversight. I will look into it later this weekend. Thanks for the headsup.

**Comment by rbtcollins** [comment]
Thanks for the PR, closing as it was merged.

**Comment by dbrgn** [comment]
This isn't yet published, right? The docs at https://docs.rs/remove_dir_all/0.8.1/remove_dir_all/fn.remove_dir_all.html still point to the non-published struct. Might be worthwhile to release a patch release soon, as using or not using `RemoveDir` may have a security impact (epen

**Comment by rbtcollins** [comment]
we will be releasing an update soon, I have a bug I'm chasing down that should be fixed too
