### ISSUE TITLE
Fails with 'Permission Denied', caused by other processes?

### ISSUE THREAD

**Issue by PhilipDaniels** [XAMPPRocky/remove_dir_all#7]
Scenario: I am trying to write a small exe to clean up build folders created by Visual Studio, bin, obj, packages etc.

If I call remove_dir_all on one of these folders while Visual Studio is open, remove_dir_all returns a Permission Denied error. If on the other hand I close Visual Studio, the exact same run of my utility succeeds.

Not sure what is causing this, but it looks like VS might have some sort of file lock on the directory? There are no problems with deleting said directories in Windows Explorer or from the command line, so do you think this is something caused by the particular way you are trying to delete the directory? I note I get the same error from std:fs::remove_dir_all, but I haven't checked the source for that yet.

**Comment by Aaronepower** [comment]
Thank you for your issue! I haven't really checked on this code in awhile and no longer use a Windows machine for development. What I can say from looking at the documentation is that if the files don't have DELETE permission then this will fail.

**Comment by rbtcollins** [comment]
This will be a sharing violation occurring. We can probably fix this with a side by side trace from either procmon or windows trace, of both the working and failing case.

**Comment by matu3ba** [comment]
@PhilipDaniels Does the issue still persist? Unfortunately you gave no information on the Windows version you are using.
I suspect it is the same problem noticed here https://github.com/XAMPPRocky/remove_dir_all/issues/34#issuecomment-1091656820, so Windows 7 (and maybe Windows 8) dont work properly.

**Comment by jm-observer** [comment]
my os is window10, but i also report the error: 
```
PS D:\hpmq> cargo generate --git http://git.netfuse.cn/iiot-pub/hpmq-wasi-template.git
Error: 拒绝访问。 (os error 5)
```

**Comment by rbtcollins** [comment]
I believe this is fixed in practice now - we now use posix semantics when it is available and fall back to older methods. Pragmatically speaking that means windows 10 will be fine, and windows 7 could still suffer problems.
