### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by XAMPPRocky** [XAMPPRocky/remove_dir_all#75]
@rbtcollins What do you think about making this crate 1.0? The public API isn't likely to change and with how stable it is I feel like it's probably time to make this 1.0. What do you think?

**Comment by rbtcollins** [comment]
I don't think we have any planned breakage lined up - I can imagine adding more to the public API, but completely happy to do that as 1.0

Should I cut a 1.0 release?

**Comment by XAMPPRocky** [comment]
Please do 🙂
